# Generated by Django 6.0 on 2025-12-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_cardpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='purchase_price',
        ),
    ]
