# Generated by Django 6.0 on 2025-12-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_remove_usercard_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpurchase',
            old_name='quanatity',
            new_name='quantity',
        ),
    ]
