# Generated by Django 6.0 on 2026-01-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_rename_quanatity_cardpurchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpurchase',
            name='is_foil',
            field=models.BooleanField(default=False),
        ),
    ]
