# Generated by Django 6.0 on 2026-01-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_cardpurchase_is_foil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CardPurchase',
        ),
    ]
