# Generated by Django 6.0 on 2026-01-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_usercard_purchase_price_delete_cardpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='purchase_price',
        ),
    ]
