# Generated by Django 6.0 on 2026-01-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_usercard_quantity_cardtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtransaction',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
