# Generated by Django 6.0 on 2026-01-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_cardtransaction_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
