# Generated by Django 6.0 on 2025-12-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scryfall_id', models.CharField(max_length=50, unique=True)),
                ('set_code', models.CharField(max_length=10)),
                ('set_name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=50)),
                ('collector_number', models.CharField(max_length=20)),
                ('finish', models.CharField(choices=[('nonfoil', 'Non-Foil'), ('foil', 'Foil')], max_length=20)),
                ('image_url', models.URLField()),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
