# Generated by Django 6.0 on 2025-12-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price_eur',
        ),
    ]
