# Generated by Django 6.0 on 2026-01-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_price_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='price_usd_foil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
