# Generated by Django 6.0 on 2026-01-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_price_usd_foil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='finish',
        ),
    ]
