# Generated by Django 6.0 on 2026-01-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price_usd_foil',
        ),
        migrations.AddField(
            model_name='card',
            name='finish',
            field=models.CharField(choices=[('foil', 'Foil'), ('nonfoil', 'Non-Foil')], default='nonfoil', max_length=10),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('scryfall_id', 'finish'), name='unique_card_printing'),
        ),
    ]
