# Generated by Django 6.0 on 2026-01-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_price_usd_foil_card_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(max_length=50),
        ),
    ]
