# Generated by Django 6.0 on 2026-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_scryfall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
